### ISSUE TITLE
How to increase the detection classes for Tiny-YOLOv3

### ISSUE THREAD

**Issue by spaul13** [wics1224/yolov3-android-tflite#4]
The number of class for tiny yolo is really small. Can u please tell me how the tiny yolo model be used to detect all the objects from coco datasets?

**Comment by wics1224** [comment]
You need to replace the model which is trained on coco datasets

**Comment by spaul13** [comment]
I already trained the tiny-yolov3 model on coco dataset and replaced it also changed the anchors as per obtained. I have five pair of anchors. I have doubts regarding how to change the **mMasks** and **mOutWidth**. Can u please help me telling how to reassign those values for my new model.

**_Right now, I am getting some error while calling mInterpreter.runforMultipleInputsOutputs() 
The error is can't copy a tensorflow object of size [1][13][13][125] to java object [1][13][13][5][25]._**

Can @wics1224 please tell me how to resolve this issue?

**Comment by wics1224** [comment]
I just submitted yad2k.py，it may help you

**Comment by spaul13** [comment]
I tried that one (yad2k.py) for yolov3-tiny weights and cfg for coco dataset and got the following error. 

**_Parsing section yolo_0
Traceback (most recent call last):
  File "yad2k.py", line 270, in <module>
    _main(parser.parse_args())
  File "yad2k.py", line 249, in _main
    'Unsupported section header type: {}'.format(section))
ValueError: Unsupported section header type: yolo_0_**

Can you please tell me how to resolve this issue?

**Comment by sonodaatom** [comment]
@wics1224 
Could you tell me the version of python and keras and tensorflow?
And may I ask you tell me how to convert yolo.h5 to yolo.tflite?
yolo.weights to yolo.h5 by yad2k.py, right?
